PRAGMA foreign_keys = ON;
CREATE TABLE user (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, email_verified INTEGER NOT NULL, image TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE session (id TEXT PRIMARY KEY, expires_at INTEGER NOT NULL, token TEXT NOT NULL UNIQUE, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, ip_address TEXT, user_agent TEXT, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE);
CREATE INDEX session_user ON session(user_id);
CREATE TABLE account (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, provider_id TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, access_token TEXT, refresh_token TEXT, id_token TEXT, access_token_expires_at INTEGER, refresh_token_expires_at INTEGER, scope TEXT, password TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX account_user ON account(user_id);
CREATE UNIQUE INDEX account_provider ON account(provider_id, account_id);
CREATE TABLE verification (id TEXT PRIMARY KEY, identifier TEXT NOT NULL, value TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX verification_identifier ON verification(identifier);
CREATE TABLE task_lists (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES user(id), name TEXT NOT NULL, color TEXT NOT NULL, google_id TEXT);
CREATE INDEX lists_owner ON task_lists(user_id);
CREATE TABLE tasks (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES user(id), list_id TEXT NOT NULL REFERENCES task_lists(id), title TEXT NOT NULL, start_date TEXT, due_date TEXT, series_id TEXT, recurring INTEGER NOT NULL DEFAULT 0, recurring_until TEXT, completed INTEGER NOT NULL DEFAULT 0, deleted INTEGER NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1, payload TEXT NOT NULL);
CREATE INDEX tasks_owner_range ON tasks(user_id, recurring, deleted, due_date);
CREATE INDEX tasks_owner_start ON tasks(user_id, start_date);
CREATE INDEX tasks_owner_series ON tasks(user_id, series_id);
CREATE INDEX tasks_owner_occurrence_date ON tasks(user_id, series_id, json_extract(payload,'$.originalDate'));
CREATE INDEX tasks_owner_list ON tasks(user_id, list_id);
CREATE TABLE settings (user_id TEXT PRIMARY KEY REFERENCES user(id), payload TEXT NOT NULL);
CREATE TABLE google_mappings (user_id TEXT NOT NULL REFERENCES user(id), entity_id TEXT NOT NULL, google_id TEXT NOT NULL, google_list_id TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 0, attempt_started TEXT, PRIMARY KEY(user_id, entity_id));
CREATE TABLE outbox (user_id TEXT NOT NULL REFERENCES user(id), entity_id TEXT NOT NULL, version INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, next_attempt INTEGER NOT NULL DEFAULT 0, error TEXT, PRIMARY KEY(user_id, entity_id));
CREATE INDEX outbox_ready ON outbox(next_attempt);
CREATE TABLE sync_locks (user_id TEXT PRIMARY KEY REFERENCES user(id), owner TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE sync_state (user_id TEXT PRIMARY KEY REFERENCES user(id), generated_on TEXT, reconnect INTEGER NOT NULL DEFAULT 0);
